# Generated by Django 4.1.1 on 2023-04-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='comics',
            options={'verbose_name': 'Комикс', 'verbose_name_plural': 'Комиксы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Том', 'verbose_name_plural': 'Тома'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.volume', verbose_name='Том'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='artist',
            field=models.CharField(default='Кто-то', max_length=255, verbose_name='Художник'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='description',
            field=models.TextField(default='Здесь будет описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='genres',
            field=models.ManyToManyField(to='blog.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='comics',
            name='writer',
            field=models.CharField(default='Кто-то', max_length=255, verbose_name='Сценарист'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='comics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comics', verbose_name='Комикс'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер тома'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comics')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
